import {icons} from "./icons"

export const SUBSCRIPTION_FREQUENCIES = ["Monthly", "Yearly"] as const;

export type SubscriptionFrequencyOption = (typeof SUBSCRIPTION_FREQUENCIES)[number];

export const SUBSCRIPTION_CATEGORIES = [
    "Entertainment",
    "AI Tools",
    "Developer Tools",
    "Design",
    "Productivity",
    "Cloud",
    "Music",
    "Other",
] as const;

export type SubscriptionCategoryOption = (typeof SUBSCRIPTION_CATEGORIES)[number];

export const SUBSCRIPTION_CATEGORY_COLORS: Record<SubscriptionCategoryOption, string> = {
    "Entertainment": "#f7d6bf",
    "AI Tools": "#d8e9f2",
    "Developer Tools": "#e8def8",
    "Design": "#f5dfb1",
    "Productivity": "#d7ecd7",
    "Cloud": "#d1e7ef",
    "Music": "#e3d8f6",
    "Other": "#efe6cf",
};

export const tabs = [
    {name: "index", title: "Home", icon: icons.home},
    {name: "subscriptions", title: "Subscriptions", icon: icons.wallet},
    {name: "insight", title: "Insight", icon: icons.activity},
    {name: "settings", title: "Settings", icon: icons.setting},
]


export const HOME_USER = {
    name: "Shree Devraj Chouhan",
};

export const HOME_BALANCE = {
    amount: 2489.48,
    nextRenewalDate: "2027-01-01T00:00:00.000Z",
};

export const UPCOMING_SUBSCRIPTIONS: UpcomingSubscription[] = [
    {
        id: "spotify",
        icon: icons.spotify,
        name: "Spotify",
        price: 5.99,
        currency: "USD",
        daysLeft: 2,
    },
    {
        id: "notion",
        icon: icons.notion,
        name: "Notion",
        price: 12.0,
        currency: "USD",
        daysLeft: 4,
    },
    {
        id: "figma",
        icon: icons.figma,
        name: "Figma",
        price: 15.0,
        currency: "USD",
        daysLeft: 6,
    },
];

export const HOME_SUBSCRIPTIONS: Subscription[] = [
    {
        id: "dropbox-premium",
        icon: icons.dropbox,
        name: "Dropbox",
        plan: "Premium",
        category: "Cloud",
        paymentMethod: "Mastercard ending in 2410",
        status: "active",
        startDate: "2025-12-09T09:00:00.000Z",
        price: 16.96,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-06-12T09:00:00.000Z",
        color: "#f7ebbf",
    },
    {
        id: "spotify-family",
        icon: icons.spotify,
        name: "Spotify",
        plan: "Family Plan",
        category: "Music",
        paymentMethod: "Visa ending in 6044",
        status: "active",
        startDate: "2025-07-11T09:30:00.000Z",
        price: 76.77,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-08-13T09:30:00.000Z",
        color: "#f9e9a5",
    },
    {
        id: "github-copilot",
        icon: icons.github,
        name: "GitHub Copilot",
        plan: "Pro Business",
        category: "Premium",
        paymentMethod: "Visa ending in 8530",
        status: "active",
        startDate: "2025-09-18T10:00:00.000Z",
        price: 49.99,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-06-13T10:00:00.000Z",
        color: "#98d6c2",
    },
    {
        id: "adobe-family",
        icon: icons.adobe,
        name: "Adobe",
        plan: "Family Plan",
        category: "Design",
        paymentMethod: "Amex ending in 4312",
        status: "active",
        startDate: "2025-03-20T08:00:00.000Z",
        price: 98.10,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-07-13T08:00:00.000Z",
        color: "#f7ebbf",
    },
    {
        id: "figma-premium",
        icon: icons.figma,
        name: "Figma",
        plan: "Premium",
        category: "Design",
        paymentMethod: "Visa ending in 2194",
        status: "active",
        startDate: "2025-01-16T13:00:00.000Z",
        price: 19.23,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-06-14T13:00:00.000Z",
        color: "#f7ebbf",
    },
    {
        id: "claude",
        icon: icons.claude,
        name: "Claude",
        plan: "Pro",
        category: "AI Tools",
        paymentMethod: "Visa ending in 1442",
        status: "active",
        startDate: "2025-02-03T12:00:00.000Z",
        price: 9.84,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-06-25T12:00:00.000Z",
        color: "#ffd84d",
    },
    {
        id: "canva",
        icon: icons.canva,
        name: "Canva",
        plan: "Studio",
        category: "Design",
        paymentMethod: "Visa ending in 7784",
        status: "active",
        startDate: "2026-05-03T16:00:00.000Z",
        price: 43.89,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-06-30T16:00:00.000Z",
        color: "#92cdbd",
    },
    {
        id: "grammarly",
        icon: icons.medium,
        name: "Grammarly",
        plan: "Premium",
        category: "Productivity",
        paymentMethod: "Visa ending in 6621",
        status: "active",
        startDate: "2025-08-24T13:00:00.000Z",
        price: 16.96,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-06-24T13:00:00.000Z",
        color: "#a7bfe2",
    },
    {
        id: "openai-team",
        icon: icons.openai,
        name: "OpenAI Team",
        plan: "Workspace",
        category: "AI Tools",
        paymentMethod: "Visa ending in 9088",
        status: "active",
        startDate: "2025-11-10T11:30:00.000Z",
        price: 92.89,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-06-18T11:30:00.000Z",
        color: "#d8e9f2",
    },
];
